# Generated by Django 4.2.11 on 2024-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
