# Generated by Django 4.2.11 on 2024-04-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0005_alter_works_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.lives'),
        ),
    ]
